const PRODUCTS = [
    {
        id: 1,
        name: "Classic Black Tee",
        category: "men",
        price: 999,
        rating: 4.3,
        newest: 36,
        description: "Soft cotton tee with clean tailoring for everyday wear.",
        image: "https://images.unsplash.com/photo-1516826957135-700dedea698c?w=700&auto=format&fit=crop",
        colors: ["Black", "White", "Olive"],
        sizes: ["S", "M", "L", "XL"]
    },
    {
        id: 2,
        name: "Linen Summer Shirt",
        category: "men",
        price: 1599,
        rating: 4.1,
        newest: 35,
        description: "Breathable linen shirt for warm-weather style.",
        image: "https://images.unsplash.com/photo-1594938328870-9623159c8c99?w=700&auto=format&fit=crop",
        colors: ["Beige", "White", "Blue"],
        sizes: ["M", "L", "XL"]
    },
    {
        id: 3,
        name: "Tailored Navy Blazer",
        category: "men",
        price: 3199,
        rating: 4.5,
        newest: 34,
        description: "Slim-fit blazer with sharp lines and premium finish.",
        image: "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=700&auto=format&fit=crop",
        colors: ["Navy", "Charcoal"],
        sizes: ["M", "L", "XL"]
    },
    {
        id: 4,
        name: "Varsity Bomber Jacket",
        category: "men",
        price: 2799,
        rating: 4.6,
        newest: 33,
        description: "Street-ready bomber with contrast ribbing.",
        image: "https://images.unsplash.com/photo-1551028719-00167b16ebc5?w=700&auto=format&fit=crop",
        colors: ["Black", "Maroon"],
        sizes: ["M", "L", "XL"]
    },
    {
        id: 5,
        name: "Cargo Utility Pants",
        category: "men",
        price: 1899,
        rating: 4.2,
        newest: 32,
        description: "Relaxed cargo fit with multiple pockets.",
        image: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=700&auto=format&fit=crop",
        colors: ["Khaki", "Black"],
        sizes: ["30", "32", "34", "36"]
    },
    {
        id: 6,
        name: "Sporty Zip Hoodie",
        category: "men",
        price: 1499,
        rating: 4.4,
        newest: 31,
        description: "Lightweight zip hoodie for everyday layering.",
        image: "https://images.unsplash.com/photo-1611312449412-6cefac5dc3e4?w=700&auto=format&fit=crop",
        colors: ["Grey", "Black", "Navy"],
        sizes: ["S", "M", "L", "XL"]
    },
    {
        id: 7,
        name: "Distressed Denim Jeans",
        category: "men",
        price: 2099,
        rating: 4.0,
        newest: 30,
        description: "Slim distressed denim with stretch comfort.",
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=700&auto=format&fit=crop",
        colors: ["Blue", "Black"],
        sizes: ["30", "32", "34", "36"]
    },
    {
        id: 8,
        name: "Printed Resort Shirt",
        category: "men",
        price: 1399,
        rating: 4.1,
        newest: 29,
        description: "Bold printed shirt for vacation style.",
        image: "https://images.unsplash.com/photo-1593032465172-8f4ce4f65761?w=700&auto=format&fit=crop",
        colors: ["White", "Mint"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 9,
        name: "Premium Polo T-Shirt",
        category: "men",
        price: 1299,
        rating: 4.3,
        newest: 28,
        description: "Classic polo in breathable pique cotton.",
        image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=700&auto=format&fit=crop",
        colors: ["Black", "White", "Navy"],
        sizes: ["M", "L", "XL"]
    },
    {
        id: 10,
        name: "Athleisure Joggers",
        category: "men",
        price: 1199,
        rating: 4.2,
        newest: 27,
        description: "Tapered joggers with soft brushed inside.",
        image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=700&auto=format&fit=crop",
        colors: ["Black", "Grey"],
        sizes: ["M", "L", "XL"]
    },
    {
        id: 11,
        name: "Minimal Crew Sweatshirt",
        category: "men",
        price: 1699,
        rating: 4.4,
        newest: 26,
        description: "Clean silhouette sweatshirt with premium finish.",
        image: "https://images.unsplash.com/photo-1527719327859-c6ce80353573?w=700&auto=format&fit=crop",
        colors: ["Olive", "Black", "Cream"],
        sizes: ["S", "M", "L", "XL"]
    },
    {
        id: 12,
        name: "Urban Check Shirt",
        category: "men",
        price: 1549,
        rating: 4.3,
        newest: 25,
        description: "Checkered shirt for modern street layering.",
        image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=700&auto=format&fit=crop",
        colors: ["Blue", "Red"],
        sizes: ["M", "L", "XL"]
    },
    {
        id: 13,
        name: "Silk Blend Dress",
        category: "women",
        price: 2899,
        rating: 4.7,
        newest: 24,
        description: "Elegant flowy silhouette perfect for evening occasions.",
        image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=700&auto=format&fit=crop",
        colors: ["Blush", "Black"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 14,
        name: "Urban Denim Jacket",
        category: "women",
        price: 2499,
        rating: 4.8,
        newest: 23,
        description: "A structured denim jacket with a modern cropped fit.",
        image: "https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=700&auto=format&fit=crop",
        colors: ["Blue", "Grey"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 15,
        name: "Pleated Midi Skirt",
        category: "women",
        price: 1899,
        rating: 4.4,
        newest: 22,
        description: "A flattering pleated skirt for work and weekends.",
        image: "https://images.unsplash.com/photo-1583496661160-fb5886a13d46?w=700&auto=format&fit=crop",
        colors: ["Cream", "Black"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 16,
        name: "Ribbed Crop Top",
        category: "women",
        price: 999,
        rating: 4.1,
        newest: 21,
        description: "Stretch ribbed top for effortless everyday fits.",
        image: "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=700&auto=format&fit=crop",
        colors: ["White", "Black", "Pink"],
        sizes: ["XS", "S", "M"]
    },
    {
        id: 17,
        name: "Satin Party Shirt",
        category: "women",
        price: 1799,
        rating: 4.5,
        newest: 20,
        description: "Glossy satin shirt for elevated party looks.",
        image: "https://images.unsplash.com/photo-1598554747436-c9293d6a588f?w=700&auto=format&fit=crop",
        colors: ["Wine", "Black"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 18,
        name: "Wide Leg Trousers",
        category: "women",
        price: 2099,
        rating: 4.6,
        newest: 19,
        description: "Fluid wide-leg fit with tailored waistband.",
        image: "https://images.unsplash.com/photo-1475180098004-ca77a66827be?w=700&auto=format&fit=crop",
        colors: ["Black", "Beige"],
        sizes: ["S", "M", "L", "XL"]
    },
    {
        id: 19,
        name: "Graphic Oversized Tee",
        category: "women",
        price: 1099,
        rating: 4.2,
        newest: 18,
        description: "Oversized fit tee with minimal front artwork.",
        image: "https://images.unsplash.com/photo-1529903384028-929ae5dccdf1?w=700&auto=format&fit=crop",
        colors: ["White", "Lavender"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 20,
        name: "Flowy Floral Dress",
        category: "women",
        price: 2399,
        rating: 4.5,
        newest: 17,
        description: "Soft floral print dress for summer styling.",
        image: "https://images.unsplash.com/photo-1495385794356-15371f348c31?w=700&auto=format&fit=crop",
        colors: ["Floral", "Blue"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 21,
        name: "Structured Blazer",
        category: "women",
        price: 2999,
        rating: 4.7,
        newest: 16,
        description: "Power blazer with a sleek double-button front.",
        image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=700&auto=format&fit=crop",
        colors: ["Black", "Camel"],
        sizes: ["S", "M", "L", "XL"]
    },
    {
        id: 22,
        name: "Co-ord Lounge Set",
        category: "women",
        price: 2199,
        rating: 4.3,
        newest: 15,
        description: "Relaxed two-piece set for chic comfort.",
        image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=700&auto=format&fit=crop",
        colors: ["Cream", "Grey"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 23,
        name: "Textured Knit Top",
        category: "women",
        price: 1299,
        rating: 4.2,
        newest: 14,
        description: "Breathable knit top with subtle texture detail.",
        image: "https://images.unsplash.com/photo-1464863979621-258859e62245?w=700&auto=format&fit=crop",
        colors: ["Beige", "Brown"],
        sizes: ["S", "M", "L"]
    },
    {
        id: 24,
        name: "High-Waist Denim",
        category: "women",
        price: 1999,
        rating: 4.4,
        newest: 13,
        description: "High-rise denim jeans with comfort stretch.",
        image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=700&auto=format&fit=crop",
        colors: ["Blue", "Indigo"],
        sizes: ["26", "28", "30", "32"]
    },
    {
        id: 25,
        name: "Gold Accent Watch",
        category: "accessories",
        price: 3499,
        rating: 4.9,
        newest: 12,
        description: "Minimal dial wristwatch with metallic gold accents.",
        image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=700&auto=format&fit=crop",
        colors: ["Gold", "Black"],
        sizes: ["One Size"]
    },
    {
        id: 26,
        name: "Leather Crossbody Bag",
        category: "accessories",
        price: 2299,
        rating: 4.6,
        newest: 11,
        description: "Compact premium bag with adjustable strap.",
        image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=700&auto=format&fit=crop",
        colors: ["Tan", "Black"],
        sizes: ["One Size"]
    },
    {
        id: 27,
        name: "Minimalist Sunglasses",
        category: "accessories",
        price: 1199,
        rating: 4.3,
        newest: 10,
        description: "UV-protected sunglasses with lightweight frame.",
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=700&auto=format&fit=crop",
        colors: ["Black", "Brown"],
        sizes: ["One Size"]
    },
    {
        id: 28,
        name: "Chunky Hoop Earrings",
        category: "accessories",
        price: 699,
        rating: 4.1,
        newest: 9,
        description: "Statement hoops to elevate everyday outfits.",
        image: "https://images.unsplash.com/photo-1635767798638-3665c8b0d3e2?w=700&auto=format&fit=crop",
        colors: ["Gold", "Silver"],
        sizes: ["One Size"]
    },
    {
        id: 29,
        name: "Canvas Tote Bag",
        category: "accessories",
        price: 899,
        rating: 4.2,
        newest: 8,
        description: "Spacious tote for everyday carry essentials.",
        image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=700&auto=format&fit=crop",
        colors: ["Cream", "Black"],
        sizes: ["One Size"]
    },
    {
        id: 30,
        name: "Layered Chain Necklace",
        category: "accessories",
        price: 849,
        rating: 4.4,
        newest: 7,
        description: "Triple-layer chain for easy styling.",
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=700&auto=format&fit=crop",
        colors: ["Gold", "Rose Gold"],
        sizes: ["One Size"]
    },
    {
        id: 31,
        name: "Premium Leather Belt",
        category: "accessories",
        price: 999,
        rating: 4.2,
        newest: 6,
        description: "Classic leather belt with brushed buckle.",
        image: "https://images.unsplash.com/photo-1624222247344-550fb60a3fca?w=700&auto=format&fit=crop",
        colors: ["Black", "Brown"],
        sizes: ["32", "34", "36", "38"]
    },
    {
        id: 32,
        name: "Street Cap",
        category: "accessories",
        price: 749,
        rating: 4.0,
        newest: 5,
        description: "Curved peak cap with minimalist branding.",
        image: "https://images.unsplash.com/photo-1529958030586-3aae4ca485ff?w=700&auto=format&fit=crop",
        colors: ["Black", "Navy", "White"],
        sizes: ["One Size"]
    },
    {
        id: 33,
        name: "Metal Strap Watch",
        category: "accessories",
        price: 2799,
        rating: 4.5,
        newest: 4,
        description: "Polished steel watch for premium looks.",
        image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=700&auto=format&fit=crop",
        colors: ["Silver", "Black"],
        sizes: ["One Size"]
    },
    {
        id: 34,
        name: "Statement Handbag",
        category: "accessories",
        price: 2599,
        rating: 4.6,
        newest: 3,
        description: "Structured handbag with sleek metal details.",
        image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=700&auto=format&fit=crop",
        colors: ["Blush", "Black"],
        sizes: ["One Size"]
    },
    {
        id: 35,
        name: "Round Dial Bracelet Watch",
        category: "accessories",
        price: 2399,
        rating: 4.4,
        newest: 2,
        description: "Bracelet-style watch with round modern dial.",
        image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=700&auto=format&fit=crop",
        colors: ["Rose Gold", "Silver"],
        sizes: ["One Size"]
    },
    {
        id: 36,
        name: "Slim Wallet",
        category: "accessories",
        price: 899,
        rating: 4.1,
        newest: 1,
        description: "Compact wallet with multiple card slots.",
        image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=700&auto=format&fit=crop",
        colors: ["Black", "Tan"],
        sizes: ["One Size"]
    }
];
